# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run_python_script:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        python -m pip install requests pandas
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Set Environment Variables
      run: |
        echo "SMTP_MAIL=${{ secrets.SMTP_MAIL }}" >> $GITHUB_ENV
        echo "SMTP_TOKEN=${{ secrets.SMTP_TOKEN }}" >> $GITHUB_ENV
        echo "LAST_EMAIL_TIMESTAMP=${{ secrets.LAST_EMAIL_TIMESTAMP }}" >> $GITHUB_ENV
    - name: Run Python script
      run: |
        python main.py
    - name: Update secret
      run: |
        gh secret set LAST_EMAIL_TIMESTAMP "$LAST_EMAIL_TIMESTAMP"
